CREATE OR REPLACE PROCEDURE DISPLAY_MASTER_PUBLICATION AS
    CURSOR C_MASTER_PUBLICATION IS
    SELECT
        PUBID,
        TYPE,
        DETAIL1,
        DETAIL2,
        DETAIL3,
        DETAIL4
    FROM
        PUBLICATION_MASTER;
BEGIN
    FOR V_C_MASTER_PUBLICATION IN C_MASTER_PUBLICATION LOOP
    
    END LOOP;
END;