SPOOL 'Task 1 Script B Output.txt'

SET ECHO ON

SET LINESIZE 1000

SET SERVEROUTPUT ON

EXECUTE PRINT_ARTICLE('TAoO09a')

EXECUTE PRINT_ARTICLE('VLDBJ21_1')

EXECUTE PRINT_ARTICLE('PVLDB4_8')

EXECUTE PRINT_ARTICLE('PVLDB4_11')

EXECUTE PRINT_ARTICLE('ICDE2011')

EXECUTE PRINT_ARTICLE('ICDE2012')

EXECUTE PRINT_ARTICLE('CIKM2009')

EXECUTE PRINT_ARTICLE('0029498')

SPOOL OFF